# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4403b4791c9005e3bfba52c46a59eb7dc576371b075d6700f03baaa9d04e885b1969276cd2dd3089c154fbebb5939efa57abeee718fb328a8798d38da89843b2

test:
  secret_key_base: 7322c95ad596890c65421ef84a2545fe4f12a711c69b3cc6a7e5410320f2fb553f9d2f63ede900dadab87a3b015e7357529e1803d8a73818087a54e6c5e7e9f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
